package main

import (
	"encoding/json"
	"net/http"
	"net/url"
)

const (
	forecastUrl = "api.worldweatheronline.com/free/v2/weather.ashx"
)

type Response struct {
	Data struct {
		Request []struct {
			Query string `json:"query"`
			Type  string `json:"type"`
		} `json:"request"`
		Days []DailyWeather `json:"weather"`
	} `json:"data"`
}

type DailyWeather struct {
	MinTempCelsius float64         `json:"mintempC"`
	MaxTempCelsius float64         `json:"maxtempC"`
	HourlyWeathers []HourlyWeather `json:"hourly"`
	UvIndex        float64         `json:"uvIndex"`
	Date           string          `json:"date"`
}

type HourlyWeather struct {
	Date       string  `json:"UTCdate"`
	Time       string  `json:"UTCtime"`
	HeatIndex  float64 `json:"HeatIndexC"`
	Temperatur float64 `json:"tempC"`
}

func GetWeather(loc string) (Response, error) {
	v := url.Values{}
	v.Add("key", *key)
	v.Add("q", loc)
	v.Add("num_of_days", "3")
	v.Add("tp", "3")
	v.Add("format", "json")
	v.Add("cc", "no")
	v.Add("extra", "utcDateTime")

	u := url.URL{}
	u.RawQuery = v.Encode()
	u.Scheme = "https"
	u.Path = forecastUrl

	resp, err := http.Get(u.String())
	if err != nil {
		return Response{}, err
	}
	defer resp.Body.Close()

	response := Response{}

	err = json.NewDecoder(resp.Body).Decode(&response)
	if err != nil {
		return Response{}, err
	}

	return response, nil
}

/*
{'data': {
  'request': [{'query': 'Koln, Germany', 'type': 'City'}],
  'weather': [{'astronomy': [{'moonrise': '12:11 AM',
      'moonset': '10:11 AM',
      'sunrise': '07:18 AM',
      'sunset': '06:12 PM'}],
    'date': '2016-02-29',
    'hourly': [{'DewPointC': '-4',
      'DewPointF': '25',
      'FeelsLikeC': '-5',
      'FeelsLikeF': '22',
      'HeatIndexC': '-1',
      'HeatIndexF': '31',
      'UTCdate': '2016-02-29',
      'UTCtime': '0',
      'WindChillC': '-5',
      'WindChillF': '22',
      'WindGustKmph': '30',
      'WindGustMiles': '19',
      'chanceoffog': '0',
      'chanceoffrost': '98',
      'chanceofhightemp': '0',
      'chanceofovercast': '0',
      'chanceofrain': '0',
      'chanceofremdry': '0',
      'chanceofsnow': '0',
      'chanceofsunshine': '98',
      'chanceofthunder': '0',
      'chanceofwindy': '0',
      'cloudcover': '8',
      'humidity': '78',
      'precipMM': '0.0',
      'pressure': '1021',
      'tempC': '0',
      'tempF': '31',
      'time': '100',
      'visibility': '10',
      'weatherCode': '113',
      'weatherDesc': [{'value': 'Clear'}],
      'weatherIconUrl': [{'value': 'http://cdn.worldweatheronline.net/images/wsymbols01_png_64/wsymbol_0008_clear_sky_night.png'}],
      'winddir16Point': 'NNE',
      'winddirDegree': '14',
      'windspeedKmph': '17',
      'windspeedMiles': '11'},
     {'DewPointC': '-4',
      'DewPointF': '25',
      'FeelsLikeC': '-6',
      'FeelsLikeF': '21',
      'HeatIndexC': '-1',
      'HeatIndexF': '30',
      'UTCdate': '2016-02-29',
      'UTCtime': '300',
      'WindChillC': '-6',
      'WindChillF': '21',
      'WindGustKmph': '28',
      'WindGustMiles': '17',
      'chanceoffog': '0',
      'chanceoffrost': '97',
      'chanceofhightemp': '0',
      'chanceofovercast': '0',
      'chanceofrain': '0',
      'chanceofremdry': '0',
      'chanceofsnow': '0',
      'chanceofsunshine': '97',
      'chanceofthunder': '0',
      'chanceofwindy': '0',
      'cloudcover': '5',
      'humidity': '81',
      'precipMM': '0.0',
      'pressure': '1021',
      'tempC': '-2',
      'tempF': '29',
      'time': '400',
      'visibility': '10',
      'weatherCode': '113',
      'weatherDesc': [{'value': 'Clear'}],
      'weatherIconUrl': [{'value': 'http://cdn.worldweatheronline.net/images/wsymbols01_png_64/wsymbol_0008_clear_sky_night.png'}],
      'winddir16Point': 'NNE',
      'winddirDegree': '16',
      'windspeedKmph': '15',
      'windspeedMiles': '9'},
     {'DewPointC': '-4',
      'DewPointF': '25',
      'FeelsLikeC': '-3',
      'FeelsLikeF': '27',
      'HeatIndexC': '1',
      'HeatIndexF': '34',
      'UTCdate': '2016-02-29',
      'UTCtime': '600',
      'WindChillC': '-3',
      'WindChillF': '27',
      'WindGustKmph': '26',
      'WindGustMiles': '16',
      'chanceoffog': '0',
      'chanceoffrost': '96',
      'chanceofhightemp': '0',
      'chanceofovercast': '0',
      'chanceofrain': '0',
      'chanceofremdry': '0',
      'chanceofsnow': '0',
      'chanceofsunshine': '96',
      'chanceofthunder': '0',
      'chanceofwindy': '0',
      'cloudcover': '2',
      'humidity': '80',
      'precipMM': '0.0',
      'pressure': '1022',
      'tempC': '0',
      'tempF': '32',
      'time': '700',
      'visibility': '10',
      'weatherCode': '113',
      'weatherDesc': [{'value': 'Clear'}],
      'weatherIconUrl': [{'value': 'http://cdn.worldweatheronline.net/images/wsymbols01_png_64/wsymbol_0008_clear_sky_night.png'}],
      'winddir16Point': 'N',
      'winddirDegree': '7',
      'windspeedKmph': '17',
      'windspeedMiles': '11'},
     {'DewPointC': '-2',
      'DewPointF': '28',
      'FeelsLikeC': '-1',
      'FeelsLikeF': '30',
      'HeatIndexC': '3',
      'HeatIndexF': '37',
      'UTCdate': '2016-02-29',
      'UTCtime': '900',
      'WindChillC': '-1',
      'WindChillF': '30',
      'WindGustKmph': '29',
      'WindGustMiles': '18',
      'chanceoffog': '0',
      'chanceoffrost': '0',
      'chanceofhightemp': '0',
      'chanceofovercast': '0',
      'chanceofrain': '0',
      'chanceofremdry': '0',
      'chanceofsnow': '0',
      'chanceofsunshine': '95',
      'chanceofthunder': '0',
      'chanceofwindy': '0',
      'cloudcover': '0',
      'humidity': '53',
      'precipMM': '0.0',
      'pressure': '1022',
      'tempC': '2',
      'tempF': '36',
      'time': '1000',
      'visibility': '10',
      'weatherCode': '113',
      'weatherDesc': [{'value': 'Sunny'}],
      'weatherIconUrl': [{'value': 'http://cdn.worldweatheronline.net/images/wsymbols01_png_64/wsymbol_0001_sunny.png'}],
      'winddir16Point': 'NNE',
      'winddirDegree': '12',
      'windspeedKmph': '16',
      'windspeedMiles': '10'},
     {'DewPointC': '-3',
      'DewPointF': '27',
      'FeelsLikeC': '3',
      'FeelsLikeF': '37',
      'HeatIndexC': '7',
      'HeatIndexF': '45',
      'UTCdate': '2016-02-29',
      'UTCtime': '1200',
      'WindChillC': '3',
      'WindChillF': '37',
      'WindGustKmph': '34',
      'WindGustMiles': '21',
      'chanceoffog': '0',
      'chanceoffrost': '0',
      'chanceofhightemp': '0',
      'chanceofovercast': '0',
      'chanceofrain': '0',
      'chanceofremdry': '0',
      'chanceofsnow': '0',
      'chanceofsunshine': '94',
      'chanceofthunder': '0',
      'chanceofwindy': '0',
      'cloudcover': '0',
      'humidity': '43',
      'precipMM': '0.0',
      'pressure': '1021',
      'tempC': '6',
      'tempF': '43',
      'time': '1300',
      'visibility': '10',
      'weatherCode': '113',
      'weatherDesc': [{'value': 'Sunny'}],
      'weatherIconUrl': [{'value': 'http://cdn.worldweatheronline.net/images/wsymbols01_png_64/wsymbol_0001_sunny.png'}],
      'winddir16Point': 'NNE',
      'winddirDegree': '26',
      'windspeedKmph': '28',
      'windspeedMiles': '17'},
     {'DewPointC': '-4',
      'DewPointF': '25',
      'FeelsLikeC': '2',
      'FeelsLikeF': '36',
      'HeatIndexC': '6',
      'HeatIndexF': '44',
      'UTCdate': '2016-02-29',
      'UTCtime': '1500',
      'WindChillC': '2',
      'WindChillF': '36',
      'WindGustKmph': '31',
      'WindGustMiles': '19',
      'chanceoffog': '0',
      'chanceoffrost': '0',
      'chanceofhightemp': '0',
      'chanceofovercast': '0',
      'chanceofrain': '0',
      'chanceofremdry': '0',
      'chanceofsnow': '0',
      'chanceofsunshine': '93',
      'chanceofthunder': '0',
      'chanceofwindy': '0',
      'cloudcover': '0',
      'humidity': '48',
      'precipMM': '0.0',
      'pressure': '1021',
      'tempC': '5',
      'tempF': '41',
      'time': '1600',
      'visibility': '10',
      'weatherCode': '113',
      'weatherDesc': [{'value': 'Sunny'}],
      'weatherIconUrl': [{'value': 'http://cdn.worldweatheronline.net/images/wsymbols01_png_64/wsymbol_0001_sunny.png'}],
      'winddir16Point': 'NNE',
      'winddirDegree': '21',
      'windspeedKmph': '26',
      'windspeedMiles': '16'},
     {'DewPointC': '-4',
      'DewPointF': '25',
      'FeelsLikeC': '-2',
      'FeelsLikeF': '28',
      'HeatIndexC': '2',
      'HeatIndexF': '35',
      'UTCdate': '2016-02-29',
      'UTCtime': '1800',
      'WindChillC': '-2',
      'WindChillF': '28',
      'WindGustKmph': '28',
      'WindGustMiles': '17',
      'chanceoffog': '0',
      'chanceoffrost': '10',
      'chanceofhightemp': '0',
      'chanceofovercast': '0',
      'chanceofrain': '0',
      'chanceofremdry': '0',
      'chanceofsnow': '0',
      'chanceofsunshine': '92',
      'chanceofthunder': '0',
      'chanceofwindy': '0',
      'cloudcover': '0',
      'humidity': '66',
      'precipMM': '0.0',
      'pressure': '1023',
      'tempC': '2',
      'tempF': '35',
      'time': '1900',
      'visibility': '10',
      'weatherCode': '113',
      'weatherDesc': [{'value': 'Clear'}],
      'weatherIconUrl': [{'value': 'http://cdn.worldweatheronline.net/images/wsymbols01_png_64/wsymbol_0008_clear_sky_night.png'}],
      'winddir16Point': 'N',
      'winddirDegree': '10',
      'windspeedKmph': '18',
      'windspeedMiles': '11'},
     {'DewPointC': '-4',
      'DewPointF': '25',
      'FeelsLikeC': '-2',
      'FeelsLikeF': '28',
      'HeatIndexC': '1',
      'HeatIndexF': '34',
      'UTCdate': '2016-02-29',
      'UTCtime': '2100',
      'WindChillC': '-2',
      'WindChillF': '28',
      'WindGustKmph': '18',
      'WindGustMiles': '11',
      'chanceoffog': '0',
      'chanceoffrost': '15',
      'chanceofhightemp': '0',
      'chanceofovercast': '0',
      'chanceofrain': '0',
      'chanceofremdry': '0',
      'chanceofsnow': '0',
      'chanceofsunshine': '91',
      'chanceofthunder': '0',
      'chanceofwindy': '0',
      'cloudcover': '0',
      'humidity': '78',
      'precipMM': '0.0',
      'pressure': '1024',
      'tempC': '0',
      'tempF': '32',
      'time': '2200',
      'visibility': '10',
      'weatherCode': '113',
      'weatherDesc': [{'value': 'Clear'}],
      'weatherIconUrl': [{'value': 'http://cdn.worldweatheronline.net/images/wsymbols01_png_64/wsymbol_0008_clear_sky_night.png'}],
      'winddir16Point': 'NNW',
      'winddirDegree': '347',
      'windspeedKmph': '12',
      'windspeedMiles': '8'}],
    'maxtempC': '6',
    'maxtempF': '43',
    'mintempC': '-2',
    'mintempF': '29',
    'uvIndex': '2'},
   {'astronomy': [{'moonrise': '01:12 AM',
      'moonset': '10:45 AM',
      'sunrise': '07:16 AM',
      'sunset': '06:14 PM'}],
    'date': '2016-03-01',
    'hourly': [{'DewPointC': '-4',
      'DewPointF': '25',
      'FeelsLikeC': '-3',
      'FeelsLikeF': '27',
      'HeatIndexC': '0',
      'HeatIndexF': '32',
      'UTCdate': '2016-03-01',
      'UTCtime': '0',
      'WindChillC': '-3',
      'WindChillF': '27',
      'WindGustKmph': '15',
      'WindGustMiles': '9',
      'chanceoffog': '0',
      'chanceoffrost': '58',
      'chanceofhightemp': '0',
      'chanceofovercast': '0',
      'chanceofrain': '0',
      'chanceofremdry': '0',
      'chanceofsnow': '0',
      'chanceofsunshine': '90',
      'chanceofthunder': '0',
      'chanceofwindy': '0',
      'cloudcover': '4',
      'humidity': '84',
      'precipMM': '0.0',
      'pressure': '1024',
      'tempC': '-1',
      'tempF': '31',
      'time': '100',
      'visibility': '10',
      'weatherCode': '113',
      'weatherDesc': [{'value': 'Clear'}],
      'weatherIconUrl': [{'value': 'http://cdn.worldweatheronline.net/images/wsymbols01_png_64/wsymbol_0008_clear_sky_night.png'}],
      'winddir16Point': 'NW',
      'winddirDegree': '325',
      'windspeedKmph': '6',
      'windspeedMiles': '4'},
     {'DewPointC': '-4',
      'DewPointF': '25',
      'FeelsLikeC': '-3',
      'FeelsLikeF': '27',
      'HeatIndexC': '-1',
      'HeatIndexF': '30',
      'UTCdate': '2016-03-01',
      'UTCtime': '300',
      'WindChillC': '-3',
      'WindChillF': '27',
      'WindGustKmph': '14',
      'WindGustMiles': '9',
      'chanceoffog': '0',
      'chanceoffrost': '87',
      'chanceofhightemp': '0',
      'chanceofovercast': '0',
      'chanceofrain': '0',
      'chanceofremdry': '0',
      'chanceofsnow': '0',
      'chanceofsunshine': '89',
      'chanceofthunder': '0',
      'chanceofwindy': '0',
      'cloudcover': '9',
      'humidity': '86',
      'precipMM': '0.0',
      'pressure': '1023',
      'tempC': '-2',
      'tempF': '29',
      'time': '400',
      'visibility': '10',
      'weatherCode': '113',
      'weatherDesc': [{'value': 'Clear'}],
      'weatherIconUrl': [{'value': 'http://cdn.worldweatheronline.net/images/wsymbols01_png_64/wsymbol_0008_clear_sky_night.png'}],
      'winddir16Point': 'NW',
      'winddirDegree': '316',
      'windspeedKmph': '6',
      'windspeedMiles': '4'},
     {'DewPointC': '-4',
      'DewPointF': '25',
      'FeelsLikeC': '-4',
      'FeelsLikeF': '25',
      'HeatIndexC': '-2',
      'HeatIndexF': '28',
      'UTCdate': '2016-03-01',
      'UTCtime': '600',
      'WindChillC': '-4',
      'WindChillF': '25',
      'WindGustKmph': '9',
      'WindGustMiles': '6',
      'chanceoffog': '0',
      'chanceoffrost': '88',
      'chanceofhightemp': '0',
      'chanceofovercast': '0',
      'chanceofrain': '0',
      'chanceofremdry': '0',
      'chanceofsnow': '0',
      'chanceofsunshine': '100',
      'chanceofthunder': '0',
      'chanceofwindy': '0',
      'cloudcover': '79',
      'humidity': '86',
      'precipMM': '0.0',
      'pressure': '1023',
      'tempC': '-3',
      'tempF': '27',
      'time': '700',
      'visibility': '10',
      'weatherCode': '119',
      'weatherDesc': [{'value': 'Cloudy'}],
      'weatherIconUrl': [{'value': 'http://cdn.worldweatheronline.net/images/wsymbols01_png_64/wsymbol_0004_black_low_cloud.png'}],
      'winddir16Point': 'W',
      'winddirDegree': '267',
      'windspeedKmph': '6',
      'windspeedMiles': '4'},
     {'DewPointC': '-3',
      'DewPointF': '27',
      'FeelsLikeC': '2',
      'FeelsLikeF': '36',
      'HeatIndexC': '2',
      'HeatIndexF': '36',
      'UTCdate': '2016-03-01',
      'UTCtime': '900',
      'WindChillC': '2',
      'WindChillF': '36',
      'WindGustKmph': '9',
      'WindGustMiles': '6',
      'chanceoffog': '0',
      'chanceoffrost': '0',
      'chanceofhightemp': '0',
      'chanceofovercast': '0',
      'chanceofrain': '0',
      'chanceofremdry': '0',
      'chanceofsnow': '0',
      'chanceofsunshine': '100',
      'chanceofthunder': '0',
      'chanceofwindy': '0',
      'cloudcover': '6',
      'humidity': '64',
      'precipMM': '0.0',
      'pressure': '1022',
      'tempC': '1',
      'tempF': '34',
      'time': '1000',
      'visibility': '10',
      'weatherCode': '113',
      'weatherDesc': [{'value': 'Sunny'}],
      'weatherIconUrl': [{'value': 'http://cdn.worldweatheronline.net/images/wsymbols01_png_64/wsymbol_0001_sunny.png'}],
      'winddir16Point': 'SE',
      'winddirDegree': '134',
      'windspeedKmph': '5',
      'windspeedMiles': '3'},
     {'DewPointC': '-6',
      'DewPointF': '22',
      'FeelsLikeC': '4',
      'FeelsLikeF': '39',
      'HeatIndexC': '7',
      'HeatIndexF': '44',
      'UTCdate': '2016-03-01',
      'UTCtime': '1200',
      'WindChillC': '4',
      'WindChillF': '39',
      'WindGustKmph': '17',
      'WindGustMiles': '11',
      'chanceoffog': '0',
      'chanceoffrost': '0',
      'chanceofhightemp': '0',
      'chanceofovercast': '1',
      'chanceofrain': '1',
      'chanceofremdry': '0',
      'chanceofsnow': '0',
      'chanceofsunshine': '100',
      'chanceofthunder': '0',
      'chanceofwindy': '0',
      'cloudcover': '48',
      'humidity': '41',
      'precipMM': '0.0',
      'pressure': '1020',
      'tempC': '4',
      'tempF': '38',
      'time': '1300',
      'visibility': '10',
      'weatherCode': '116',
      'weatherDesc': [{'value': 'Partly Cloudy'}],
      'weatherIconUrl': [{'value': 'http://cdn.worldweatheronline.net/images/wsymbols01_png_64/wsymbol_0002_sunny_intervals.png'}],
      'winddir16Point': 'SW',
      'winddirDegree': '234',
      'windspeedKmph': '8',
      'windspeedMiles': '5'},
     {'DewPointC': '-4',
      'DewPointF': '26',
      'FeelsLikeC': '5',
      'FeelsLikeF': '40',
      'HeatIndexC': '7',
      'HeatIndexF': '45',
      'UTCdate': '2016-03-01',
      'UTCtime': '1500',
      'WindChillC': '5',
      'WindChillF': '40',
      'WindGustKmph': '18',
      'WindGustMiles': '11',
      'chanceoffog': '0',
      'chanceoffrost': '0',
      'chanceofhightemp': '0',
      'chanceofovercast': '2',
      'chanceofrain': '28',
      'chanceofremdry': '0',
      'chanceofsnow': '0',
      'chanceofsunshine': '0',
      'chanceofthunder': '0',
      'chanceofwindy': '0',
      'cloudcover': '77',
      'humidity': '46',
      'precipMM': '0.1',
      'pressure': '1018',
      'tempC': '7',
      'tempF': '45',
      'time': '1600',
      'visibility': '10',
      'weatherCode': '176',
      'weatherDesc': [{'value': 'Patchy rain nearby'}],
      'weatherIconUrl': [{'value': 'http://cdn.worldweatheronline.net/images/wsymbols01_png_64/wsymbol_0009_light_rain_showers.png'}],
      'winddir16Point': 'SW',
      'winddirDegree': '221',
      'windspeedKmph': '14',
      'windspeedMiles': '9'},
     {'DewPointC': '-1',
      'DewPointF': '30',
      'FeelsLikeC': '-1',
      'FeelsLikeF': '31',
      'HeatIndexC': '4',
      'HeatIndexF': '38',
      'UTCdate': '2016-03-01',
      'UTCtime': '1800',
      'WindChillC': '-1',
      'WindChillF': '31',
      'WindGustKmph': '34',
      'WindGustMiles': '21',
      'chanceoffog': '0',
      'chanceoffrost': '0',
      'chanceofhightemp': '0',
      'chanceofovercast': '4',
      'chanceofrain': '83',
      'chanceofremdry': '0',
      'chanceofsnow': '0',
      'chanceofsunshine': '0',
      'chanceofthunder': '0',
      'chanceofwindy': '0',
      'cloudcover': '88',
      'humidity': '72',
      'precipMM': '0.8',
      'pressure': '1015',
      'tempC': '4',
      'tempF': '38',
      'time': '1900',
      'visibility': '9',
      'weatherCode': '296',
      'weatherDesc': [{'value': 'Light rain'}],
      'weatherIconUrl': [{'value': 'http://cdn.worldweatheronline.net/images/wsymbols01_png_64/wsymbol_0033_cloudy_with_light_rain_night.png'}],
      'winddir16Point': 'S',
      'winddirDegree': '188',
      'windspeedKmph': '19',
      'windspeedMiles': '12'},
     {'DewPointC': '2',
      'DewPointF': '36',
      'FeelsLikeC': '0',
      'FeelsLikeF': '31',
      'HeatIndexC': '2',
      'HeatIndexF': '35',
      'UTCdate': '2016-03-01',
      'UTCtime': '2100',
      'WindChillC': '0',
      'WindChillF': '31',
      'WindGustKmph': '40',
      'WindGustMiles': '25',
      'chanceoffog': '0',
      'chanceoffrost': '0',
      'chanceofhightemp': '0',
      'chanceofovercast': '51',
      'chanceofrain': '82',
      'chanceofremdry': '0',
      'chanceofsnow': '0',
      'chanceofsunshine': '0',
      'chanceofthunder': '0',
      'chanceofwindy': '0',
      'cloudcover': '100',
      'humidity': '85',
      'precipMM': '2.4',
      'pressure': '1013',
      'tempC': '0',
      'tempF': '31',
      'time': '2200',
      'visibility': '9',
      'weatherCode': '296',
      'weatherDesc': [{'value': 'Light rain'}],
      'weatherIconUrl': [{'value': 'http://cdn.worldweatheronline.net/images/wsymbols01_png_64/wsymbol_0033_cloudy_with_light_rain_night.png'}],
      'winddir16Point': 'SSW',
      'winddirDegree': '205',
      'windspeedKmph': '23',
      'windspeedMiles': '14'}],
    'maxtempC': '7',
    'maxtempF': '45',
    'mintempC': '0',
    'mintempF': '31',
    'uvIndex': '2'},
   {'astronomy': [{'moonrise': '02:10 AM',
      'moonset': '11:25 AM',
      'sunrise': '07:14 AM',
      'sunset': '06:15 PM'}],
    'date': '2016-03-02',
    'hourly': [{'DewPointC': '3',
      'DewPointF': '38',
      'FeelsLikeC': '1',
      'FeelsLikeF': '33',
      'HeatIndexC': '5',
      'HeatIndexF': '41',
      'UTCdate': '2016-03-02',
      'UTCtime': '0',
      'WindChillC': '1',
      'WindChillF': '33',
      'WindGustKmph': '46',
      'WindGustMiles': '28',
      'chanceoffog': '0',
      'chanceoffrost': '0',
      'chanceofhightemp': '0',
      'chanceofovercast': '24',
      'chanceofrain': '81',
      'chanceofremdry': '0',
      'chanceofsnow': '0',
      'chanceofsunshine': '0',
      'chanceofthunder': '0',
      'chanceofwindy': '0',
      'cloudcover': '100',
      'humidity': '87',
      'precipMM': '0.3',
      'pressure': '1010',
      'tempC': '5',
      'tempF': '41',
      'time': '100',
      'visibility': '2',
      'weatherCode': '266',
      'weatherDesc': [{'value': 'Light drizzle'}],
      'weatherIconUrl': [{'value': 'http://cdn.worldweatheronline.net/images/wsymbols01_png_64/wsymbol_0033_cloudy_with_light_rain_night.png'}],
      'winddir16Point': 'SSW',
      'winddirDegree': '212',
      'windspeedKmph': '24',
      'windspeedMiles': '15'},
     {'DewPointC': '4',
      'DewPointF': '39',
      'FeelsLikeC': '5',
      'FeelsLikeF': '41',
      'HeatIndexC': '8',
      'HeatIndexF': '46',
      'UTCdate': '2016-03-02',
      'UTCtime': '300',
      'WindChillC': '5',
      'WindChillF': '41',
      'WindGustKmph': '52',
      'WindGustMiles': '32',
      'chanceoffog': '0',
      'chanceoffrost': '0',
      'chanceofhightemp': '0',
      'chanceofovercast': '51',
      'chanceofrain': '80',
      'chanceofremdry': '0',
      'chanceofsnow': '0',
      'chanceofsunshine': '0',
      'chanceofthunder': '0',
      'chanceofwindy': '0',
      'cloudcover': '100',
      'humidity': '90',
      'precipMM': '0.9',
      'pressure': '1007',
      'tempC': '7',
      'tempF': '45',
      'time': '400',
      'visibility': '9',
      'weatherCode': '296',
      'weatherDesc': [{'value': 'Light rain'}],
      'weatherIconUrl': [{'value': 'http://cdn.worldweatheronline.net/images/wsymbols01_png_64/wsymbol_0033_cloudy_with_light_rain_night.png'}],
      'winddir16Point': 'SW',
      'winddirDegree': '228',
      'windspeedKmph': '19',
      'windspeedMiles': '12'},
     {'DewPointC': '5',
      'DewPointF': '41',
      'FeelsLikeC': '5',
      'FeelsLikeF': '41',
      'HeatIndexC': '8',
      'HeatIndexF': '46',
      'UTCdate': '2016-03-02',
      'UTCtime': '600',
      'WindChillC': '5',
      'WindChillF': '41',
      'WindGustKmph': '42',
      'WindGustMiles': '26',
      'chanceoffog': '0',
      'chanceoffrost': '0',
      'chanceofhightemp': '0',
      'chanceofovercast': '57',
      'chanceofrain': '100',
      'chanceofremdry': '0',
      'chanceofsnow': '0',
      'chanceofsunshine': '0',
      'chanceofthunder': '0',
      'chanceofwindy': '0',
      'cloudcover': '100',
      'humidity': '93',
      'precipMM': '1.0',
      'pressure': '1005',
      'tempC': '7',
      'tempF': '45',
      'time': '700',
      'visibility': '2',
      'weatherCode': '293',
      'weatherDesc': [{'value': 'Patchy light rain'}],
      'weatherIconUrl': [{'value': 'http://cdn.worldweatheronline.net/images/wsymbols01_png_64/wsymbol_0033_cloudy_with_light_rain_night.png'}],
      'winddir16Point': 'WSW',
      'winddirDegree': '240',
      'windspeedKmph': '14',
      'windspeedMiles': '9'},
     {'DewPointC': '4',
      'DewPointF': '40',
      'FeelsLikeC': '2',
      'FeelsLikeF': '36',
      'HeatIndexC': '7',
      'HeatIndexF': '44',
      'UTCdate': '2016-03-02',
      'UTCtime': '900',
      'WindChillC': '2',
      'WindChillF': '36',
      'WindGustKmph': '39',
      'WindGustMiles': '24',
      'chanceoffog': '0',
      'chanceoffrost': '0',
      'chanceofhightemp': '0',
      'chanceofovercast': '4',
      'chanceofrain': '78',
      'chanceofremdry': '0',
      'chanceofsnow': '0',
      'chanceofsunshine': '1',
      'chanceofthunder': '0',
      'chanceofwindy': '0',
      'cloudcover': '100',
      'humidity': '84',
      'precipMM': '1.0',
      'pressure': '1004',
      'tempC': '7',
      'tempF': '44',
      'time': '1000',
      'visibility': '9',
      'weatherCode': '296',
      'weatherDesc': [{'value': 'Light rain'}],
      'weatherIconUrl': [{'value': 'http://cdn.worldweatheronline.net/images/wsymbols01_png_64/wsymbol_0017_cloudy_with_light_rain.png'}],
      'winddir16Point': 'W',
      'winddirDegree': '272',
      'windspeedKmph': '33',
      'windspeedMiles': '21'},
     {'DewPointC': '1',
      'DewPointF': '34',
      'FeelsLikeC': '4',
      'FeelsLikeF': '39',
      'HeatIndexC': '8',
      'HeatIndexF': '47',
      'UTCdate': '2016-03-02',
      'UTCtime': '1200',
      'WindChillC': '4',
      'WindChillF': '39',
      'WindGustKmph': '43',
      'WindGustMiles': '27',
      'chanceoffog': '0',
      'chanceoffrost': '0',
      'chanceofhightemp': '0',
      'chanceofovercast': '0',
      'chanceofrain': '41',
      'chanceofremdry': '0',
      'chanceofsnow': '0',
      'chanceofsunshine': '27',
      'chanceofthunder': '0',
      'chanceofwindy': '0',
      'cloudcover': '31',
      'humidity': '62',
      'precipMM': '0.4',
      'pressure': '1004',
      'tempC': '8',
      'tempF': '47',
      'time': '1300',
      'visibility': '9',
      'weatherCode': '176',
      'weatherDesc': [{'value': 'Patchy rain nearby'}],
      'weatherIconUrl': [{'value': 'http://cdn.worldweatheronline.net/images/wsymbols01_png_64/wsymbol_0009_light_rain_showers.png'}],
      'winddir16Point': 'W',
      'winddirDegree': '271',
      'windspeedKmph': '36',
      'windspeedMiles': '22'},
     {'DewPointC': '0',
      'DewPointF': '31',
      'FeelsLikeC': '4',
      'FeelsLikeF': '38',
      'HeatIndexC': '8',
      'HeatIndexF': '46',
      'UTCdate': '2016-03-02',
      'UTCtime': '1500',
      'WindChillC': '4',
      'WindChillF': '38',
      'WindGustKmph': '38',
      'WindGustMiles': '24',
      'chanceoffog': '0',
      'chanceoffrost': '0',
      'chanceofhightemp': '0',
      'chanceofovercast': '26',
      'chanceofrain': '59',
      'chanceofremdry': '0',
      'chanceofsnow': '0',
      'chanceofsunshine': '100',
      'chanceofthunder': '47',
      'chanceofwindy': '0',
      'cloudcover': '46',
      'humidity': '56',
      'precipMM': '0.1',
      'pressure': '1003',
      'tempC': '8',
      'tempF': '46',
      'time': '1600',
      'visibility': '10',
      'weatherCode': '176',
      'weatherDesc': [{'value': 'Patchy rain nearby'}],
      'weatherIconUrl': [{'value': 'http://cdn.worldweatheronline.net/images/wsymbols01_png_64/wsymbol_0009_light_rain_showers.png'}],
      'winddir16Point': 'WSW',
      'winddirDegree': '255',
      'windspeedKmph': '31',
      'windspeedMiles': '19'},
     {'DewPointC': '3',
      'DewPointF': '37',
      'FeelsLikeC': '2',
      'FeelsLikeF': '36',
      'HeatIndexC': '7',
      'HeatIndexF': '44',
      'UTCdate': '2016-03-02',
      'UTCtime': '1800',
      'WindChillC': '2',
      'WindChillF': '36',
      'WindGustKmph': '33',
      'WindGustMiles': '21',
      'chanceoffog': '0',
      'chanceoffrost': '0',
      'chanceofhightemp': '0',
      'chanceofovercast': '53',
      'chanceofrain': '75',
      'chanceofremdry': '0',
      'chanceofsnow': '0',
      'chanceofsunshine': '40',
      'chanceofthunder': '5',
      'chanceofwindy': '0',
      'cloudcover': '62',
      'humidity': '77',
      'precipMM': '0.1',
      'pressure': '1001',
      'tempC': '7',
      'tempF': '44',
      'time': '1900',
      'visibility': '10',
      'weatherCode': '176',
      'weatherDesc': [{'value': 'Patchy rain nearby'}],
      'weatherIconUrl': [{'value': 'http://cdn.worldweatheronline.net/images/wsymbols01_png_64/wsymbol_0025_light_rain_showers_night.png'}],
      'winddir16Point': 'SW',
      'winddirDegree': '235',
      'windspeedKmph': '27',
      'windspeedMiles': '17'},
     {'DewPointC': '3',
      'DewPointF': '38',
      'FeelsLikeC': '1',
      'FeelsLikeF': '34',
      'HeatIndexC': '6',
      'HeatIndexF': '42',
      'UTCdate': '2016-03-02',
      'UTCtime': '2100',
      'WindChillC': '1',
      'WindChillF': '34',
      'WindGustKmph': '44',
      'WindGustMiles': '27',
      'chanceoffog': '0',
      'chanceoffrost': '0',
      'chanceofhightemp': '0',
      'chanceofovercast': '0',
      'chanceofrain': '74',
      'chanceofremdry': '0',
      'chanceofsnow': '0',
      'chanceofsunshine': '24',
      'chanceofthunder': '25',
      'chanceofwindy': '0',
      'cloudcover': '42',
      'humidity': '83',
      'precipMM': '0.1',
      'pressure': '1001',
      'tempC': '6',
      'tempF': '42',
      'time': '2200',
      'visibility': '10',
      'weatherCode': '176',
      'weatherDesc': [{'value': 'Patchy rain nearby'}],
      'weatherIconUrl': [{'value': 'http://cdn.worldweatheronline.net/images/wsymbols01_png_64/wsymbol_0025_light_rain_showers_night.png'}],
      'winddir16Point': 'WSW',
      'winddirDegree': '247',
      'windspeedKmph': '31',
      'windspeedMiles': '19'}],
    'maxtempC': '8',
    'maxtempF': '47',
    'mintempC': '4',
    'mintempF': '39',
    'uvIndex': '2'}]}}
*/
